baseurl = "https://kanarbed.netlify.com"
title = "Kan ar Bed, Un Voyage Musical Autour du Monde - CD & livre-CD événement"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
enableRobotsTXT = true

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "kanarbed"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
googleAnalytics = "UA-126206970-1"

[languages.fr]
  languageName = "Français"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.fr.menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/about/"
    name = "A propos"
    weight = 2
  [[languages.fr.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

[languages.br]
  languageName = "Breton"

  [[languages.br.menu.main]]
    url = "/"
    name = "Accueil (br)"
    weight = 1
  [[languages.br.menu.main]]
    url = "/about/"
    name = "A propos (br)"
    weight = 2
  [[languages.br.menu.main]]
    url = "/contact/"
    name = "Contact (br)"
    weight = 3

[languages.en]
  languageName = "English"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

# Links format

[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Kan ar Bed"

  # Date format (default: Jan 2, 2006)
  # date_format = "Jan 2, 2006"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5
