baseurl = "https://www.kanarbed.bzh"
title = "Kan ar Bed, Un Voyage Musical Autour du Monde - CD & livre-CD événement"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
enableRobotsTXT = true

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "kanarbed"

disableKinds = ["taxonomy", "taxonomyTerm"]
#[taxonomies]
  #tag = ""
  #category = ""

# Google analytics
googleAnalytics = "UA-126206970-1"

[languages.fr]
  languageName = "Français"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.fr.menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 2

#[languages.br]
#  languageName = "Breton"

#  [[languages.br.menu.main]]
#    url = "/"
#    name = "Accueil (br)"
#    weight = 1
#  [[languages.br.menu.main]]
#    url = "/contact/"
#    name = "Contact (br)"
#    weight = 2

#[languages.en]
#  languageName = "English"

#  [[languages.en.menu.main]]
#    url = "/"
#    name = "Home"
#    weight = 1
#  [[languages.en.menu.main]]
#    url = "/contact/"
#   name = "Contact"
#   weight = 2

# Links format